[package]
name = "cascade_core"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.43.1", default-features = false, features = [
    "cross_join",
    "csv",
] }
petgraph = "0.6.5"
rustworkx-core = "0.15.1"
geo = "0.29.1"
rstar = "0.12.0"
thiserror = "1.0.63"
osm4routing = "0.7.0"
ahash = "0.8.11"
itertools = "0.13.0"

[dev-dependencies]
approx = "0.5.1"
