name: Coverage

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
    coverage:
        name: Run coverage
        runs-on: ubuntu-latest
        strategy:
          matrix:
            rust:
              - stable
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"
          SQLX_OFFLINE: true
        steps:
          - name: Checkout sources
            uses: actions/checkout@v2
          - name: Install toolchain
            uses: actions-rs/toolchain@v1
            with:
              toolchain: ${{ matrix.rust }}
              override: true
              components: llvm-tools-preview
          - name: Install cargo-llvm-cov
            uses: taiki-e/install-action@cargo-llvm-cov
          - name: Generate code coverage
            id: coverage
            run: cargo llvm-cov --all-features --exclude register_derive_impl --workspace --no-fail-fast --lcov --output-path lcov.info
            env:
              NODE_COVERALLS_DEBUG: true

          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@v3
            with:
               # token: ${{ secrets.CODECOV_ORG_TOKEN }} # not required for public repos
               files: lcov.info
               fail_ci_if_error: true
